CREATE TABLE REGISTRATION_USERS (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_USERNAME (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;